// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const evenFibonacciNumbers = () => {
	let sumEvens = 2;

	let n1 = 1;
	let n2 = 2;
	let nextTerm = 0;

	while (nextTerm <= 4000000) {
		nextTerm = n1 + n2;
		n1 = n2;
		n2 = nextTerm;

		console.log(nextTerm);
		if (nextTerm % 2 === 0) sumEvens += nextTerm;
	}

	console.log(`Sum of the even-valued terms: ${sumEvens}`);
};

evenFibonacciNumbers();
